### ISSUE TITLE
Aufgabe 1 

### ISSUE THREAD

**Issue by ceotimritter** [Romina-Dubrow/Wissenschaftliches-Arbeiten-Gruppenarbeit#10]
Dieses issues ist zur Bearbeitung von Aufgabe 1 von Luca Sauer und Tim Ritter.
Die Anderen dürfen sich, das nicht angucken.

**Comment by ceotimritter** [comment]
Ich hab für die 1) bereits den Code geschrieben.
Wir müssen dann bei den anderen Teilaufgaben über die Wahrscheinlichkeiten diskutieren.
Vielleicht mit _zwei_  Branches ?

**Comment by lucasauer** [comment]
> Ich hab für die 1) bereits den Code geschrieben.
> Wir müssen dann bei den anderen Teilaufgaben über die Wahrscheinlichkeiten diskutieren.
> Vielleicht mit _zwei_ Branches ?

_zwei_ Branches dafür sind eine sehr gute Idee

**Comment by ceotimritter** [comment]
Ich hab jetzt schon mal einen Code hochgeladen.
Ich würde vorschlagen, dass wir die Aufgabe bis Sonntag separat lösen und schauen welche Teile des Codes für jeweils übernehmen. :)

**Comment by lucasauer** [comment]
Perfekt, danke. Das können wir so machen

**Comment by lucasauer** [comment]
Hab schon mal ne Pull Request (#16) mit meinem Vorschlag für die Aufgabe gemacht ✌️

**Comment by ceotimritter** [comment]
Ich hab einen Datensatz hochgeladen. 🤔 
Wenn du denkst der Datensatz ist gut, können wir den anderen Bescheid sagen, dass wir die Aufgabe 3 anfangen können. :)

**Comment by lucasauer** [comment]
Ja genau. Wir können dann denk ich auch den Aufgabe 1-Branch schon mit dem main-Branch mergen, oder?
