### ISSUE TITLE
Aufgabe 5)

### ISSUE THREAD

**Issue by lucasauer** [Romina-Dubrow/Wissenschaftliches-Arbeiten-Gruppenarbeit#12]
Diskussion

**Comment by KathrinHenkenherm** [comment]
okay, die Analyse ist fertig, ich füge das Fazit mal hier nochmal ein:

# Die Studierenden im Datensatz sind 20 bis 32 Jahre alt (Durchschnitt 25, Standardabweichung 2.3).
# Die Studienfaecher sind nicht gleichverteilt. Statistik tritt am haeufigsten auf. 
# Mehr Studierende hatten Mathe LK. Das arithmetische Mittel und der Median des Alters bei Studierenden, die Mathe LK hatten, ist aehnlich zu dem der Studierenden, die keinen Mathe LK hatten. Trotzdem streut das Alter bei den Studierenden ohne Mathe LK staerker.
# Mathematikinteresse war im Median und Modalwert 5, Programmierinteresse 4.
# Programmierinteresse streut stärker als Mathematikinteresse.
# Studierende, die Mathe LK hatten, haben ein hoeheres Mathematikinteresse.
# Studierende mit Mathe LK hatten ein gleichverteiltes Programmierinteresse (scheint keinen Zusammenhang zu haben).
# Programmierinteresse ist bei Studierenden ohne Mathe-LK staerker als bei Studierenden mit Mathe LK.
# Es gibt einen deutlichen Zusammenhang zwischen der Wahl des Studienfachs und der Belegung vom Mathe LK.
# Mathematikinteresse nach Studienfaechern: Mathe > Statistik > Data Science > Informatik.
# Programmierinteresse nach Studienfaechern: Informatik > Data Science > Statistik > Mathe.

wie waren denn die tatsächlichen Zusammenhänge zwischen den Variablen, @lucasauer  und @ceotimritter ? :)

**Comment by lucasauer** [comment]
Alsooo, die Alter-Variable ist normalverteilt mit Erwartungswert 25 und Standardabweichung 2. Da haben dann die Zufallszahlen anscheinend ein bisschen mehr gestreut. Es stimmt auf jeden Fall, dass die Studienfächer nicht gleichverteilt sind und Statistik eins der beiden wahrscheinlichsten war. Habt ihr zufällig auch rausbekommen, welches am seltensten vorkommt? :)

**Comment by lucasauer** [comment]
Ist auch gut, dass zwischen dem Alter bei Mathe LK ja und nein kaum ein Unterschied ist, weil zumindest haben wir da keinen Zusammenhang eingebaut :D

**Comment by ceotimritter** [comment]
Und noch kurz zur Variabel Mathe - LK:

Jede Person, die Mathematik studiert oder eine mathematische Interesse von größer als 5 hat, belegte Mathe-Lk in der Schule.
Falls die Person Statistik studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 30% Mathe-Lk.
Falls die Person Data Science studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 20% Mathe-Lk.
Falls die Person Informatik studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 10% Mathe-Lk.

Ich mein ihr habt das zwar schon grob umschrieben, aber hier mal die tatsächlichen Zusammenhänge. :)

**Comment by annahdk** [comment]
> Und noch kurz zur Variabel Mathe - LK:
> 
> Jede Person, die Mathematik studiert oder eine mathematische Interesse von größer als 5 hat, belegte Mathe-Lk in der Schule.
> Falls die Person Statistik studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 30% Mathe-Lk.
> Falls die Person Data Science studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 20% Mathe-Lk.
> Falls die Person Informatik studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 10% Mathe-Lk.
> 
> Ich mein ihr habt das zwar schon grob umschrieben, aber hier mal die tatsächlichen Zusammenhänge. :)

 super danke, wir hatten durch den Kontingenzkoeffizienten bisher nur die Interpretation vorgenommen, _dass_ es Zusammenhänge hier gibt, ohne genau sagen zu können welche

**Comment by Romina-Dubrow** [comment]
> Alsooo, die Alter-Variable ist normalverteilt mit Erwartungswert 25 und Standardabweichung 2. Da haben dann die Zufallszahlen anscheinend ein bisschen mehr gestreut. Es stimmt auf jeden Fall, dass die Studienfächer nicht gleichverteilt sind und Statistik eins der beiden wahrscheinlichsten war. Habt ihr zufällig auch rausbekommen, welches am seltensten vorkommt? :)

Mathe oder? Ich habe meine Funktion nämlich nochmal so angewendet:
e(Daten$Studienfach[Mathe.LK=="Ja"])

 Quantilbasierte Kategorisierung: 
 ------------------------
 Niedrig: Data Science Informatik Mathematik 
 Mittel:  
 Hoch: Statistik 
  ------------------------
Und da kam es mir schon sehr verdächtig vor, dass Mathestudenten beim Mathe LK so selten vorkommen.

**Comment by Romina-Dubrow** [comment]
Mir fällt gerade auf, dass wir gar nicht so viele Grundeigenschaften des Datensatzes zusammengetragen haben. Also wie viel Leute befragt wurden, wie viel Leute welches Studienfach studieren, usw.
Wollen wir das vielleicht noch schnell nachholen?

**Comment by KathrinHenkenherm** [comment]
> Und noch kurz zur Variabel Mathe - LK:
> 
> Jede Person, die Mathematik studiert oder eine mathematische Interesse von größer als 5 hat, belegte Mathe-Lk in der Schule.
> Falls die Person Statistik studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 30% Mathe-Lk.
> Falls die Person Data Science studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 20% Mathe-Lk.
> Falls die Person Informatik studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 10% Mathe-Lk.
> 
> Ich mein ihr habt das zwar schon grob umschrieben, aber hier mal die tatsächlichen Zusammenhänge. :)

ah cool, das passt auch mit den Plots überein, wenn mans so liest :) wie ist das denn mit Zusammenhängen zwischen Interesse an Mathematik/ Programmieren und Studienfach?

**Comment by leia-b** [comment]
> Mir fällt gerade auf, dass wir gar nicht so viele Grundeigenschaften des Datensatzes zusammengetragen haben. Also wie viel Leute befragt wurden, wie viel Leute welches Studienfach studieren, usw.
> Wollen wir das vielleicht noch schnell nachholen?

Ich hab gerade mal was hinzugefügt :)

Das bestätigt auch, dass Mathe das seltenste Studienfach war mit nur 15 Nennungen, insgesamt haben wir Daten von 100 "Teilnehmern".

**Comment by ceotimritter** [comment]
> > Und noch kurz zur Variabel Mathe - LK:
> > Jede Person, die Mathematik studiert oder eine mathematische Interesse von größer als 5 hat, belegte Mathe-Lk in der Schule.
> > Falls die Person Statistik studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 30% Mathe-Lk.
> > Falls die Person Data Science studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 20% Mathe-Lk.
> > Falls die Person Informatik studiert und eine mathematische Interesse von maximal 5 hat, hatte er/sie mit einer Wahrscheinlichkeit von 10% Mathe-Lk.
> > Ich mein ihr habt das zwar schon grob umschrieben, aber hier mal die tatsächlichen Zusammenhänge. :)
> 
> ah cool, das passt auch mit den Plots überein, wenn mans so liest :) wie ist das denn mit Zusammenhängen zwischen Interesse an Mathematik/ Programmieren und Studienfach?

Also die Interesse an Mathematik/ Programmieren nach Studienfächern ist so wie du das oben schon beschrieben hast.
Wir haben dann zufällige Wert zwischen 1 (weniger interessiert) und 7 (sehr interessiert) gezogen, wobei Studienfächer mit hoher Interesse eine höhere Wahrscheinlichkeit für größere Wert haben als die anderen.

Soll ich die Wahrscheinlichkeiten auch noch sagen?

**Comment by KathrinHenkenherm** [comment]
danke, und schön, dass das mit der Analyse übereinstimmt :) die konkreten Wahrscheinlichkeiten brauch ich nicht, jetzt darf ich ja auch ins Skript gucken :)

**Comment by Romina-Dubrow** [comment]
Ok super, dann haben wir ja eigentlich alles, oder? Wollen wir die Issues dann schließen und die Gruppenaufgabe beenden? :)
