### ISSUE TITLE
Aufgabe 4)

### ISSUE THREAD

**Issue by annahdk** [Romina-Dubrow/Wissenschaftliches-Arbeiten-Gruppenarbeit#13]
Analyse

**Comment by KathrinHenkenherm** [comment]
da die Funktionen ja jetzt soweit fertig sind und nur noch ein bisschen Doku fehlt könnten wir mit der Analyse des Datensatzes anfangen, oder? :)

**Comment by Romina-Dubrow** [comment]
Wie machen wir das am Besten? Jeder verwendet seine eigene Funktion und die zwei anderen machen die beiden mit den wenigsten Commits? :)

**Comment by annahdk** [comment]
Ich habe mal einen Aufgabe 4 - Branch erstellt und ein Dokument hineingeladen, das wir dann füllen können 

Die Idee dass wir mit unseren eigenen Funktionen anfangen finde ich gut !

**Comment by Romina-Dubrow** [comment]
Wollen wir vielleicht noch eine Textdatei erstellen  in der wir unsere Ergebnisse beschreiben können? Die können wir dann ja auch gut Luca und Tim zeigen, wenn wir in Aufgabe 5 alles besprechen!

**Comment by KathrinHenkenherm** [comment]
> Wollen wir vielleicht noch eine Textdatei erstellen in der wir unsere Ergebnisse beschreiben können? Die können wir dann ja auch gut Luca und Tim zeigen, wenn wir in Aufgabe 5 alles besprechen!

oder direkt R Markdown? so oder so müssen wir unsere Ergebnisse auf jeden Fall dokumentieren

**Comment by annahdk** [comment]
> > Wollen wir vielleicht noch eine Textdatei erstellen in der wir unsere Ergebnisse beschreiben können? Die können wir dann ja auch gut Luca und Tim zeigen, wenn wir in Aufgabe 5 alles besprechen!
> 
> oder direkt R Markdown? so oder so müssen wir unsere Ergebnisse auf jeden Fall dokumentieren

ich habe jetzt erstmal direkt in das R Skript geschrieben, aber wir können gerne die Ergebnisse in einem Text zusammenfassen und in einer Textdatei bzw. Markdown Datei den anderen präsentieren (also zB in den Aufgabe 5 Branch als Auftakt laden)

**Comment by Romina-Dubrow** [comment]
Ok Markdown finde ich auch sehr gut! Dann sieht man sowohl was wir gemacht haben als auch den zugehörigen Text

**Comment by leia-b** [comment]
Wer macht jetzt noch die Auswertung mit den Funktionen von Luca und Tim?

Die von Luca könnte ich mitmachen (ist ja sehr nah an meiner Funktion dran), es sei denn, einer von euch möchte das gerne machen :)

**Comment by KathrinHenkenherm** [comment]
> Wer macht jetzt noch die Auswertung mit den Funktionen von Luca und Tim?
> 
> Die von Luca könnte ich mitmachen (ist ja sehr nah an meiner Funktion dran), es sei denn, einer von euch möchte das gerne machen :)

ich kann auf jeden Fall noch was machen, mit welcher Funktion ist mir egal, also machst du die deskr von Luca und ich die deskr_d von Tim?

**Comment by leia-b** [comment]
> > Wer macht jetzt noch die Auswertung mit den Funktionen von Luca und Tim?
> > Die von Luca könnte ich mitmachen (ist ja sehr nah an meiner Funktion dran), es sei denn, einer von euch möchte das gerne machen :)
> 
> ich kann auf jeden Fall noch was machen, mit welcher Funktion ist mir egal, also machst du die deskr von Luca und ich die deskr_d von Tim?

Können wir gerne so machen, wenn Anna und Romina das so okay finden.

**Comment by annahdk** [comment]
> > > Wer macht jetzt noch die Auswertung mit den Funktionen von Luca und Tim?
> > > Die von Luca könnte ich mitmachen (ist ja sehr nah an meiner Funktion dran), es sei denn, einer von euch möchte das gerne machen :)
> > 
> > 
> > ich kann auf jeden Fall noch was machen, mit welcher Funktion ist mir egal, also machst du die deskr von Luca und ich die deskr_d von Tim?
> 
> Können wir gerne so machen, wenn Anna und Romina das so okay finden.

jaa danke euch

**Comment by leia-b** [comment]
Ich glaube, wir haben jetzt alle Funktionen.
Sollen wir noch ein gemeinsames Fazit formulieren?

**Comment by Romina-Dubrow** [comment]
Danke! 
Ich wollte auch noch meine Ausformulierungen hinzufügen!
Aber dann wäre ich auch für ein gemeinsames Fazit

**Comment by Romina-Dubrow** [comment]
Mir ist gerade aufgefallen, dass es vielleicht noch interessant wäre bei meiner Funktion einen Boxplot zu erstellen. Ich weiß das ist ein bisschen spät, aber eigentlich gebe ich ja nur die Daten für den Boxplot am Ende aus und es ist vielleicht interessant das nochmal visualisiert zu sehen. 
Beim Überfliegen der anderen Funktionen habe ich zumindest keinen gesehen, aber vielleicht habe ich das auch übersehen 
Es bringt jetzt auch nicht so viel aber ich dachte einfach nur dass es ganz cool aussieht. 
Naja, ihr könnt ja mal sagen was ihr davon haltet :)

**Comment by KathrinHenkenherm** [comment]
> Mir ist gerade aufgefallen, dass es vielleicht noch interessant wäre bei meiner Funktion einen Boxplot zu erstellen. Ich weiß das ist ein bisschen spät, aber eigentlich gebe ich ja nur die Daten für den Boxplot am Ende aus und es ist vielleicht interessant das nochmal visualisiert zu sehen.
> Beim Überfliegen der anderen Funktionen habe ich zumindest keinen gesehen, aber vielleicht habe ich das auch übersehen
> Es bringt jetzt auch nicht so viel aber ich dachte einfach nur dass es ganz cool aussieht.
> Naja, ihr könnt ja mal sagen was ihr davon haltet :)

die Funktion deskr_d erzeugt auch Boxplots für die metrische Variable getrennt nach den beiden Klassen der dichotomen Variable, aber wir könnten im allgemeinen Boxplots betrachten, schreib da gerne was wenn du möchtest :)

**Comment by KathrinHenkenherm** [comment]
> Ich glaube, wir haben jetzt alle Funktionen.
> Sollen wir noch ein gemeinsames Fazit formulieren?

finde ich gut, in welcher Form wollen wir das Fazit denn jetzt zusammenstellen?

**Comment by Romina-Dubrow** [comment]
> > Mir ist gerade aufgefallen, dass es vielleicht noch interessant wäre bei meiner Funktion einen Boxplot zu erstellen. Ich weiß das ist ein bisschen spät, aber eigentlich gebe ich ja nur die Daten für den Boxplot am Ende aus und es ist vielleicht interessant das nochmal visualisiert zu sehen.
> > Beim Überfliegen der anderen Funktionen habe ich zumindest keinen gesehen, aber vielleicht habe ich das auch übersehen
> > Es bringt jetzt auch nicht so viel aber ich dachte einfach nur dass es ganz cool aussieht.
> > Naja, ihr könnt ja mal sagen was ihr davon haltet :)
> 
> die Funktion deskr_d erzeugt auch Boxplots für die metrische Variable getrennt nach den beiden Klassen der dichotomen Variable, aber wir könnten im allgemeinen Boxplots betrachten, schreib da gerne was wenn du möchtest :)

Achso, dann ist das glaube ich nicht unbedingt nötig, aber danke!

**Comment by Romina-Dubrow** [comment]
> > Ich glaube, wir haben jetzt alle Funktionen.
> > Sollen wir noch ein gemeinsames Fazit formulieren?
> 
> finde ich gut, in welcher Form wollen wir das Fazit denn jetzt zusammenstellen?

Wollen wir das einfach auch als Kommentar ans Ende schreiben?

**Comment by Romina-Dubrow** [comment]
Ich hab mal ein kurzes Fazit ans Ende geschrieben, ihr könnt das gerne noch verbessern und ergänzen wenn euch was auffällt :)

**Comment by leia-b** [comment]
> Ich hab mal ein kurzes Fazit ans Ende geschrieben, ihr könnt das gerne noch verbessern und ergänzen wenn euch was auffällt :)

Super, Dankeschön! :)
Hab alles, was mir noch eingefallen ist dazu geschrieben.

**Comment by annahdk** [comment]
Ich habe auch nochmal die Funktionen geordnet und ein wenig ergänzt!

**Comment by Romina-Dubrow** [comment]
Ok wenn Kathrin dann keine Einwände mehr hat können wir auch mit Aufgabe 5 anfangen oder?

**Comment by annahdk** [comment]
Ja gerne!
