### ISSUE TITLE
Planung

### ISSUE THREAD

**Issue by annahdk** [Romina-Dubrow/Wissenschaftliches-Arbeiten-Gruppenarbeit#2]
Sollen wir uns Donnerstag bei Zoom treffen um Leia und Kathrin hinzuzufügen und  die Aufgaben aufteilen?

**Comment by annahdk** [comment]
Hier können wir ja alles Organisatorische klären *_*

**Comment by lucasauer** [comment]
> Sollen wir uns Donnerstag bei Zoom treffen um Leia und Kathrin hinzuzufügen und die Aufgaben aufteilen?

Das ist eine gute Idee! 👍🏻

**Comment by Romina-Dubrow** [comment]
Ja, ich habe ihnen schon Bescheid gesagt!

**Comment by Romina-Dubrow** [comment]
Wer möchte denn in der Aufgabe 1 den R Code erstellen?

**Comment by ceotimritter** [comment]
> Wer möchte denn in der Aufgabe 1 den R Code erstellen?

Wenn sich keiner meldet, könnte ich das machen.

**Comment by KathrinHenkenherm** [comment]
> Wer möchte denn in der Aufgabe 1 den R Code erstellen?

also ich würde lieber die Analyse in Aufgabe 4 machen...

**Comment by leia-b** [comment]
Ich möchte auch lieber Aufgabe 4 machen

**Comment by lucasauer** [comment]
> Wer möchte denn in der Aufgabe 1 den R Code erstellen?

Ich könnte das machen

**Comment by Romina-Dubrow** [comment]
Okay, super!

**Comment by annahdk** [comment]
Perfekt - es gibt pro Aufgabe auch schon ein Milestone, in dem zu Aufgabe 3 können wir über die diesbezügliche Aufteilung der Funktionenerstellung diskutieren.

**Comment by Romina-Dubrow** [comment]
Wollen wir dann immer unsere Issues mit help wanted labeln wenn wir irgendwo nicht weiterkommen?

**Comment by ceotimritter** [comment]
Luca hat den Datensatz grad hochgeladen.
Das heißt wir können jetzt die Aufgabe 3 machen.

**Comment by lucasauer** [comment]
> Luca hat den Datensatz grad hochgeladen.
> Das heißt wir können jetzt die Aufgabe 3 machen.

Genau, ist auch schon (aus Versehen) im Main Branch :D

**Comment by KathrinHenkenherm** [comment]
ich bin ein bisschen verwirrt, an welchen der Funktionen in den pull requests wird jetzt nicht mehr gearbeitet? die könnten wir dann ja schonmal in main mergen

**Comment by KathrinHenkenherm** [comment]
und vielleicht die Hilfsfunktionen in ein zweites Skript auslagern?

**Comment by annahdk** [comment]
> ich bin ein bisschen verwirrt, an welchen der Funktionen in den pull requests wird jetzt nicht mehr gearbeitet? die könnten wir dann ja schonmal in main mergen

jaa geht mir ähnlich. ich glaube, prinzipiell kann alles gemerget werden, weil wir ja nicht parallel an den gleichen Aufgaben gearbeitet haben, oder? man kann dann ja immer noch sachen ändern

**Comment by KathrinHenkenherm** [comment]
> > ich bin ein bisschen verwirrt, an welchen der Funktionen in den pull requests wird jetzt nicht mehr gearbeitet? die könnten wir dann ja schonmal in main mergen
> 
> jaa geht mir ähnlich. ich glaube, prinzipiell kann alles gemerget werden, weil wir ja nicht parallel an den gleichen Aufgaben gearbeitet haben, oder? man kann dann ja immer noch sachen ändern

ja klar, und Korrekturen gehen immer, ich wollte jetzt nur nichts mergen an dem aktuell noch verändert wird, da wärs dann sinnvoll noch zu warten

**Comment by lucasauer** [comment]
Meine kann auf jeden Fall schon gemerged werden. Werde da nichts mehr dran ändern

**Comment by lucasauer** [comment]
Ich denke, wir sollten uns dann auch bald mal mit der README-Datei auseinandersetzen und da so die wichtigsten Infos ergänzen

**Comment by leia-b** [comment]
Ich hab schonmal ein Dokument für die Hilfsfunktionen erstellt und meine hinzugefügt :)

**Comment by KathrinHenkenherm** [comment]
> Ich hab schonmal ein Dokument für die Hilfsfunktionen erstellt und meine hinzugefügt :)

ich hab meine dann auch rübergeschoben =)

**Comment by Romina-Dubrow** [comment]
Dann mache ich das bei mir auch mal 😺

**Comment by Romina-Dubrow** [comment]
> Ich denke, wir sollten uns dann auch bald mal mit der README-Datei auseinandersetzen und da so die wichtigsten Infos ergänzen

Was genau geben wir da denn an? Einfach dass wir verschiedene Codes für jede Aufgabe haben, dass es bei Aufgabe 3 noch Hilfsfunktionen gibt usw.? Ich habe das noch nicht so richtig verstanden. Finde es aber auch sehr sinnvoll wenn wir uns damit auseinandersetzen!

**Comment by leia-b** [comment]
> > Ich denke, wir sollten uns dann auch bald mal mit der README-Datei auseinandersetzen und da so die wichtigsten Infos ergänzen
> 
> Was genau geben wir da denn an? Einfach dass wir verschiedene Codes für jede Aufgabe haben, dass es bei Aufgabe 3 noch Hilfsfunktionen gibt usw.? Ich habe das noch nicht so richtig verstanden. Finde es aber auch sehr sinnvoll wenn wir uns damit auseinandersetzen!

Ich glaube wir sollen unsere Funktionen dokumentieren, so wie bei R-Hilfeseiten
Also kurz beschreiben, was die Funktion macht und welche Argumente diese erwartet.
Die Beispiele an denen wir unsere Funktionen getestet haben können da sicherlich auch rein.

Mehr fällt mir jetzt auch nicht ein..

**Comment by lucasauer** [comment]
Ja genau, so in die Richtung. In der Lösungsskizze zu dem Übungsblatt zu GitHub auf Moodle steht ziemlich genau, was wir dazu schreiben sollten/können :)

**Comment by Romina-Dubrow** [comment]
Ah ok danke! Das muss ich wohl überlesen haben :)

**Comment by ceotimritter** [comment]
Brauchen wir noch die anderen Branches?
Ich fände es ganz gut, wenn wir nur die main - Branch aktiv haben.
