### ISSUE TITLE
Wer kann welche Funktionen schreiben?

### ISSUE THREAD

**Issue by leia-b** [Romina-Dubrow/Wissenschaftliches-Arbeiten-Gruppenarbeit#3]
(a) Eine Funktion, die verschiedene geeignete deskriptive Statistiken
für metrische Variablen berechnet und ausgibt
(b) Eine Funktion, die verschiedene geeignete deskriptive Statistiken
für kategoriale Variablen berechnet und ausgibt
(c) Eine Funktion, die geeignete deskriptive bivariate Statistiken für
den Zusammenhang zwischen zwei kategorialen Variablen
berechnet ausgibt
(d) Eine Funktion, die geeignete deskriptive bivariate Statistiken für
den Zusammengang zwischen einer metrischen und einer
dichotomen Variablen berechnet und ausgibt
(e) Eine Funktion, die eine mindestens ordinal skalierte Variable
quantilbasiert kategorisiert (z.B. in „niedrig“, „mittel“, „hoch“)
(f) Eine Funktion, die eine geeignete Visualisierung von drei oder vier
kategorialen Variablen erstellt
Freiwillig: weitere zur Deskription und Visualisierung geeignete
Funktionen

**Comment by Romina-Dubrow** [comment]
Es sieht so aus als ob die Funktionen ein wenig aufeinander aufbauen. Dann müssten diejenigen mit ähnlichen Funktionen am besten zusammen arbeiten

**Comment by annahdk** [comment]
klingt sinnvoll

**Comment by KathrinHenkenherm** [comment]
für die Funktion a): min, mean, man, var vielleicht? für Funktion b) nur Anzahlen?

**Comment by Romina-Dubrow** [comment]
was genau ist mit kategorial gemeint?

**Comment by annahdk** [comment]
für b) geht bei ordinal auch der median oder?

**Comment by annahdk** [comment]
> was genau ist mit kategorial gemeint?

ordinale und nominale Daten denke ich

**Comment by KathrinHenkenherm** [comment]
> für b) geht bei ordinal auch der median oder?

stimmt!

**Comment by Romina-Dubrow** [comment]
> > was genau ist mit kategorial gemeint?
> 
> ordinale und nominale Daten denke ich

Danke!

**Comment by Romina-Dubrow** [comment]
> für b) geht bei ordinal auch der median oder?

Dann gehen da auch Quantile

Außerdem kann man für alle ein Stabdiagramm und den Modus verwenden

**Comment by leia-b** [comment]
Bei c) kann man für ordinale Merkmale den Rangkorrelationskoeffizienten nehmen und für nominale Merkmale den Kontingenzkoeffizienten nehmen, oder?

**Comment by ceotimritter** [comment]
> > für b) geht bei ordinal auch der median oder?
> 
> Dann gehen da auch Quantile
> 
> Außerdem kann man für alle ein Stabdiagramm und den Modus verwenden

Eine quantilbasierte Kategorisierung ist auch bei der e)  gefragt

**Comment by lucasauer** [comment]
Sollen bei der f) die drei bzw. vier Variablen gleichzeitig dargestellt werden?

**Comment by KathrinHenkenherm** [comment]
> Sollen bei der f) die drei bzw. vier Variablen gleichzeitig dargestellt werden?

ich denke schon

**Comment by lucasauer** [comment]
Eine Helferfunktion könnte ja z.B. sein, die Variablen mit "ja" und "nein" als Ausprägung in TRUE und FALSE oder 1 und 0 umzuwandeln, oder?

**Comment by lucasauer** [comment]
> > Sollen bei der f) die drei bzw. vier Variablen gleichzeitig dargestellt werden?
> 
> ich denke schon

okay

**Comment by annahdk** [comment]
zu d): es gibt den Phi-Koeffizienten speziell für dichotome Merkmale

**Comment by Romina-Dubrow** [comment]
Bei der e) kann man bestimmt gut Faktoren verwenden, oder?

**Comment by ceotimritter** [comment]
Wollen wir jetzt vielleicht mal die **Teilaufgaben** zulotsen?
Dann kann sich jeder zu seinem Thema _Gedanken machen_ und danach können wir weiter diskutieren

**Comment by leia-b** [comment]
Wir können ja für jede Funktion ein _Issue_ erstellen und die dann zuweisen :)

**Comment by annahdk** [comment]
> Wollen wir jetzt vielleicht mal die **Teilaufgaben** zulotsen?
> Dann kann sich jeder zu seinem Thema _Gedanken machen_ und danach können wir weiter diskutieren :)

Vorschlag: a) Luca b) Leia c) Anna d) Tim e) Romina f) Kathrin

**Comment by ceotimritter** [comment]
Das sind zwei sehr gute Ideen

**Comment by Romina-Dubrow** [comment]
Soll ich dann dieses Issue closen?

**Comment by ceotimritter** [comment]
Ist denn alles geklärt?

**Comment by Romina-Dubrow** [comment]
**ja**

**Comment by lucasauer** [comment]
Ja denke schon @ceotimritter

**Comment by ceotimritter** [comment]
wunderbärchen, dann kannst du das closen

**Comment by annahdk** [comment]
von mir aus 

> Soll ich dann dieses Issue closen?

von mir aus
