### ISSUE TITLE
Aufgabe 3 e)

### ISSUE THREAD

**Issue by Romina-Dubrow** [Romina-Dubrow/Wissenschaftliches-Arbeiten-Gruppenarbeit#7]
Eine Funktion, die eine mindestens ordinal skalierte Variable
quantilbasiert kategorisiert (z.B. in „niedrig“, „mittel“, „hoch“)

**Comment by Romina-Dubrow** [comment]
Also ich habe mal angefangen meine Funktion zu schreiben.
Jetzt bin ich am überlegen, weil da steht, dass ich die Variablen kategorisieren soll.
Meint ihr ich soll dann eine Art Dataframe erstellen sowas wie:
Beispiel Schulnoten: 1>2>3>4>5>6
niedrig       mittel      hoch
5                    3              2
6                    4              1

oder soll ich einen Vektoren bilden, die dann "niedrig" , "hoch",... heißen und die passenden Einträge enthalten?  oder eine Liste? 
Es gibt so viele Möglichkeiten und ich bin überfordert haha

**Comment by Romina-Dubrow** [comment]
Außerdem frage ich mich wie das mit den ordinalen Daten dann klappt.
Müssen die dann schon vorher zumindest in der richtigen Reihenfolge in ihrem Vektor stehen?
Weil, wenn wir das Beispiel Abschlüsse haben mit x=c("Hochschulreife", "Bachelor", "Master) passt es wenn ich den Vektor einfach so als Faktor erstelle mit factor(x,ordered=TRUE, levels=x) und sage "Hochschulreife" < "Bachelor" < "Master"
Wenn der Vektor aber irgendwie so aussieht: x=c("Master", "Hochschulreife", "Bachelor") geht das natürlich schief.

**Comment by KathrinHenkenherm** [comment]
> Also ich habe mal angefangen meine Funktion zu schreiben.
> Jetzt bin ich am überlegen, weil da steht, dass ich die Variablen kategorisieren soll.
> Meint ihr ich soll dann eine Art Dataframe erstellen sowas wie:
> Beispiel Schulnoten: 1>2>3>4>5>6
> niedrig mittel hoch
> 5 3 2
> 6 4 1
> 
> oder soll ich einen Vektoren bilden, die dann "niedrig" , "hoch",... heißen und die passenden Einträge enthalten? oder eine Liste?
> Es gibt so viele Möglichkeiten und ich bin überfordert haha

die Aufgabe heißt ja quantilbasiert kategorisieren, also würde ich die Kategorien von den Quantilen abhängig machen, z.B. alle Werte unter dem 25%-Qantil sind niedrig, alle über dem 75%-Qantil sind hoch und die dazwischen mittel

**Comment by KathrinHenkenherm** [comment]
> Außerdem frage ich mich wie das mit den ordinalen Daten dann klappt.
> Müssen die dann schon vorher zumindest in der richtigen Reihenfolge in ihrem Vektor stehen?
> Weil, wenn wir das Beispiel Abschlüsse haben mit x=c("Hochschulreife", "Bachelor", "Master) passt es wenn ich den Vektor einfach so als Faktor erstelle mit factor(x,ordered=TRUE, levels=x) und sage "Hochschulreife" < "Bachelor" < "Master"
> Wenn der Vektor aber irgendwie so aussieht: x=c("Master", "Hochschulreife", "Bachelor") geht das natürlich schief.

du musst den Faktor ja nicht mit den Vektor als level-Eingabe erstellen, das klappt ja spätestens bei Wiederholungen nicht mehr, außerdem ist der ordered factor ja schon da, die Funktion muss ihn ja nur verarbeiten

**Comment by Romina-Dubrow** [comment]
> > Also ich habe mal angefangen meine Funktion zu schreiben.
> > Jetzt bin ich am überlegen, weil da steht, dass ich die Variablen kategorisieren soll.
> > Meint ihr ich soll dann eine Art Dataframe erstellen sowas wie:
> > Beispiel Schulnoten: 1>2>3>4>5>6
> > niedrig mittel hoch
> > 5 3 2
> > 6 4 1
> > oder soll ich einen Vektoren bilden, die dann "niedrig" , "hoch",... heißen und die passenden Einträge enthalten? oder eine Liste?
> > Es gibt so viele Möglichkeiten und ich bin überfordert haha
> 
> die Aufgabe heißt ja quantilbasiert kategorisieren, also würde ich die Kategorien von den Quantilen abhängig machen, z.B. alle Werte unter dem 25%-Qantil sind niedrig, alle über dem 75%-Qantil sind hoch und die dazwischen mittel

Ja, das habe ich auch gemacht, aber ich weiß nur nicht genau wie ich die Kategorien dann ausgeben soll. Finde es irgendwie sinnlos einfach nur einen Vektor mit der Kategorie auszugeben

**Comment by Romina-Dubrow** [comment]
> > Außerdem frage ich mich wie das mit den ordinalen Daten dann klappt.
> > Müssen die dann schon vorher zumindest in der richtigen Reihenfolge in ihrem Vektor stehen?
> > Weil, wenn wir das Beispiel Abschlüsse haben mit x=c("Hochschulreife", "Bachelor", "Master) passt es wenn ich den Vektor einfach so als Faktor erstelle mit factor(x,ordered=TRUE, levels=x) und sage "Hochschulreife" < "Bachelor" < "Master"
> > Wenn der Vektor aber irgendwie so aussieht: x=c("Master", "Hochschulreife", "Bachelor") geht das natürlich schief.
> 
> du musst den Faktor ja nicht mit den Vektor als level-Eingabe erstellen, das klappt ja spätestens bei Wiederholungen nicht mehr, außerdem ist der ordered factor ja schon da, die Funktion muss ihn ja nur verarbeiten

Die Wiederholungen könnte ich ja auch einfach mit unique () lösen. 
Ich weiß nicht genau was du mit ordered factor meinst. Ich denke mal wir bekommen einen Vektor mit x Einträgen, die alle ordinal sind. Gibt es dann noch einen extra Vektor, der die Ordnung anzeigt?
Vielleicht habe ich auch irgendwas in der Aufgabenstellung übersehen.
Aber schonmal danke!

**Comment by KathrinHenkenherm** [comment]
> > > Also ich habe mal angefangen meine Funktion zu schreiben.
> > > Jetzt bin ich am überlegen, weil da steht, dass ich die Variablen kategorisieren soll.
> > > Meint ihr ich soll dann eine Art Dataframe erstellen sowas wie:
> > > Beispiel Schulnoten: 1>2>3>4>5>6
> > > niedrig mittel hoch
> > > 5 3 2
> > > 6 4 1
> > > oder soll ich einen Vektoren bilden, die dann "niedrig" , "hoch",... heißen und die passenden Einträge enthalten? oder eine Liste?
> > > Es gibt so viele Möglichkeiten und ich bin überfordert haha
> > 
> > 
> > die Aufgabe heißt ja quantilbasiert kategorisieren, also würde ich die Kategorien von den Quantilen abhängig machen, z.B. alle Werte unter dem 25%-Qantil sind niedrig, alle über dem 75%-Qantil sind hoch und die dazwischen mittel
> 
> Ja, das habe ich auch gemacht, aber ich weiß nur nicht genau wie ich die Kategorien dann ausgeben soll. Finde es irgendwie sinnlos einfach nur einen Vektor mit der Kategorie auszugeben

ah okay, dann habe ich deine Frage nicht ganz verstanden, ich hätte wahrscheinlich mit dem Vektor der Werte und dem der Kategorien einen data frame erstellt, die Lösung mit der Liste ist jetzt aber auch gut!

**Comment by KathrinHenkenherm** [comment]
> > > Außerdem frage ich mich wie das mit den ordinalen Daten dann klappt.
> > > Müssen die dann schon vorher zumindest in der richtigen Reihenfolge in ihrem Vektor stehen?
> > > Weil, wenn wir das Beispiel Abschlüsse haben mit x=c("Hochschulreife", "Bachelor", "Master) passt es wenn ich den Vektor einfach so als Faktor erstelle mit factor(x,ordered=TRUE, levels=x) und sage "Hochschulreife" < "Bachelor" < "Master"
> > > Wenn der Vektor aber irgendwie so aussieht: x=c("Master", "Hochschulreife", "Bachelor") geht das natürlich schief.
> > 
> > 
> > du musst den Faktor ja nicht mit den Vektor als level-Eingabe erstellen, das klappt ja spätestens bei Wiederholungen nicht mehr, außerdem ist der ordered factor ja schon da, die Funktion muss ihn ja nur verarbeiten
> 
> Die Wiederholungen könnte ich ja auch einfach mit unique () lösen.
> Ich weiß nicht genau was du mit ordered factor meinst. Ich denke mal wir bekommen einen Vektor mit x Einträgen, die alle ordinal sind. Gibt es dann noch einen extra Vektor, der die Ordnung anzeigt?
> Vielleicht habe ich auch irgendwas in der Aufgabenstellung übersehen.
> Aber schonmal danke!

mit ordered factor meinte ich eigentlich nur einen factor mit Sortierung, entschuldige die Verwirrung^^

**Comment by Romina-Dubrow** [comment]
Alles gut, danke dass du mit überlegt hast! Ich war irgendwie auch etwas verwirrt von der Aufgabe!
Ich hoffe es passt jetzt so wie ich es hochgeladen hab :)
